name: CI/CD para EC2 pública

on:
  push:
    branches:
      - main # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configuração do ambiente (Exemplo: Node.js)
      # Remova ou substitua esta seção de acordo com sua tecnologia
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # 3. Build da aplicação (Se for uma aplicação que precisa ser construída, ex: React, Angular, Vue)
      - name: Instalar Dependências e Fazer Build
        run: |
          pwd
          ls -la
          npm install
          npm run build --if-present 
          # Se sua app não precisar de build, remova esta etapa
        working-directory: /home/runner/work/projetos-2cco/

      # 4. Deploy (Transferência de arquivos e execução de comandos remotos)
      - name: Copiar arquivos e Deploy (Usando SSH com rsync)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/ec2-user/frontend
          # ARGS para rsync: -rltgoDzvO para cópia recursiva, compressão e outros
          ARGS: "-rltgoDzvO --delete" 
          # SOURCE: O que será copiado. Pode ser o diretório de build (ex: ./dist)
          SOURCE: "./dist" 

      # 5. Reiniciar o serviço no EC2 (Comando remoto)
      # Esta etapa é crucial para garantir que a nova versão do código comece a rodar
      - name: Executar comandos remotos após o deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Exemplo de comando: reiniciar um processo com PM2 ou Nginx
            # Substitua pelo comando de reinício do seu serviço
            # cd ${{ secrets.TARGET_DIR }}
            # pm2 restart meu-app
            echo "Deploy concluído. Reiniciei o serviço se necessário."
